/**********************************************************************************
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Icons under 'icons/fugue' are made by Yusuke Kamiyamane http://www.pinvoke.com/.
 * Licensed under a Creative Commons Attribution 3.0 license.
 * <http://creativecommons.org/licenses/by/3.0/>
 *
 *********************************************************************************/
package org.hyperic.hypclipse.plugin;

/**
 * In addition to field data from the 'New Project' wizard pages, this interface
 * provides choices made by the user that are unique to creating a new plug-in
 * project.
 * 
 */
public interface IPluginFieldData extends IFieldData {
	/**
	 * The class name field.
	 * 
	 * @return the name of the plug-in class
	 */
	String getClassname();

	/**
	 * UI plug-in selection.
	 * 
	 * @return <code>true</code> if the plug-in contains UI code and
	 *         extensions, <code>false</code> otherwise.
	 */
	boolean isUIPlugin();

	/**
	 * Plug-in class generation selection.
	 * 
	 * @return <code>true</code> if the plug-in class is to be generated by
	 *         the plug-in wizard, <code>false</code> otherwise.
	 */
	boolean doGenerateClass();

}
